sudo: required
language: node_js
node_js:
- '6'
- node

services:
  - docker

before_install:
  - export TZ=Africa/Nairobi
  - date
  - npm install -g node-gyp
  - cp $TRAVIS_BUILD_DIR/conf/config.example.json $TRAVIS_BUILD_DIR/conf/config.json
  - docker build -t $DOCKER_IMAGE:$TRAVIS_BRANCH .
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - sshpass
script:
- docker ps
- npm test
env:
  - CXX=g++-5
after_success:
  - echo "Successful"