sudo: required
language: node_js
node_js:
- '6'
- node
before_install:
  - export TZ=Africa/Nairobi
  - date
  - npm install -g node-gyp
  - cp $TRAVIS_BUILD_DIR/conf/config.example.json $TRAVIS_BUILD_DIR/conf/config.json
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - sshpass
script:
- npm test
env:
  - CXX=g++-5
after_success:
  - mv * $TRAVIS_BRANCH
  - tar -czf etlbuild.tgz $TRAVIS_BRANCH
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -o stricthostkeychecking=no etlbuild.tgz $DEPLOY_USER@$DEPLOY_HOST:./
  - sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST ./deploy-build.sh