sudo: required
language: node_js
node_js:
  - '6'
  - node

services:
  - docker

before_install:
  - export TZ=Africa/Nairobi
  - date
  - npm install -g node-gyp
  - cp $TRAVIS_BUILD_DIR/conf/config.example.json $TRAVIS_BUILD_DIR/conf/config.json
  - echo $DOCKER_PASSWORD | docker login --username=$DOCKER_USERNAME --password-stdin

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - sshpass

script:
  - npm test

env:
  - CXX=g++-5
  
after_success:
  - echo "BUILD IMAGE"
  - docker build -f docker/etl-rest-server/Dockerfile -t tankip/etl-services:${TRAVIS_BRANCH} .
  - docker push tankip/etl-services:${TRAVIS_BRANCH}