sudo: required
language: node_js
node_js:
- '6'
- node

services:
  - docker

before_install:
  - export TZ=Africa/Nairobi
  - date
  - npm install -g node-gyp
  - cp $TRAVIS_BUILD_DIR/conf/config.example.json $TRAVIS_BUILD_DIR/conf/config.json

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - sshpass
script:
- npm test
env:
  - CXX=g++-5
after_success:
  - echo "BUILD IMAGE"
  - docker build -t $DOCKER_IMAGE/$TRAVIS_BRANCH:$TRAVIS_BRANCH .
  - docker save -o $DOCKER_IMAGE-$TRAVIS_BRANCH.tar $DOCKER_IMAGE/$TRAVIS_BRANCH
  - docker images
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -o stricthostkeychecking=no $DOCKER_IMAGE-$TRAVIS_BRANCH.tar $DEPLOY_USER@$DEPLOY_HOST:/home/rtanui
  - sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST ./deploy-build.sh